project:
  type: website
  output-dir: docs

website:
  title: "Dr Kedir Ahmed"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Resume"
        file: Resume.qmd
      - text: "Publications"
        file: publication.qmd
    right:
      - icon: github
        href: https://github.com/KedirYimamA
      - icon: twitter
        href: https://x.com/KedirYAhmed

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
